resources:
- name: git-test
  type: git
  source: 
    url: https://github.com/SergeyKulagin/Docker.git
    branch: master

jobs:
- name: git-navi
  plan:
  - get: git-test
    trigger: true
  - task: annoy2
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: ubuntu
      run:
        path: echo
        args: ["Hey! Listen - git updated"]