resources:
- name: git-project
  type: git
  source: 
    uri: https://SergeyKulagin@bitbucket.org/SergeyKulagin/samples.git
    branch: master

jobs: 
- name: git-complex
  plan:
  - get: git-project
    trigger: true
  - task: t1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: maven
          tag: 3-jdk-8-alpine
      inputs:
      - name: git-project
      run: 
        path: ./git-project/ci/build.sh

